```kotlin
internal class UpgradeGesturesToControls : PreferenceUpgrade(5) {
    // ...
    override fun upgrade(preferences: SharedPreferences) {
        // ...
        upgradeGestureToBinding(preferences, "binding_FLIP_OR_ANSWER_RECOMMENDED", FLIP_OR_ANSWER_EASE3)
        upgradeGestureToBinding(preferences, "binding_FLIP_OR_ANSWER_BETTER_THAN_RECOMMENDED", FLIP_OR_ANSWER_EASE4)
        // ...
    }
    // ...
}
```