```kotlin
        "customButtonBury",
        "customButtonSuspend",
        "customButtonDelete",
        "customButtonRescheduleCard",
        "customButtonEnableWhiteboard",
        "customButtonToggleStylus",
        "customButtonSaveWhiteboard",
        "customButtonWhiteboardPenColor",
        "customButtonShowHideWhiteboard",
        "customButtonClearWhiteboard"
    )
}
```