```kotlin
// ...
val preferencesWhoseChangesShouldBeReported = setOf(
    // ...
    "binding_FLIP_OR_ANSWER_EASE1",
    "binding_FLIP_OR_ANSWER_EASE2",
    "binding_FLIP_OR_ANSWER_EASE3",
    "binding_FLIP_OR_ANSWER_EASE4",
    // ...
)
// ...
```